### ISSUE TITLE
Team dogfood spec

### ISSUE THREAD

**Issue by chriswaclawek** [dxos/teamwork#375]
# DXOS Teamwork dogfood spec for non technical people (Nov 2020)

### Notes:
* GOAL: Ship minimum viable version for internal DXOS team dogfood. All the team calls should have agendas/notes inside Teamwork. Calls up to 3 people should be hosted on Teamwork itself.
* LIMITATION: We should be able to ship this dogfood version in about 7 days. Major redesign of UX/UI is our of scope.
* REQUIREMENT: While we are aware of legacy clunky UX/UI, it should be smooth user experience for non technical team members, allowing for real world use for daily ... well, teamwork.
* First pass done by Chris, now up for review by Alex.

**KUBE/Console:**
- [ ] Default screen leads to apps https://github.com/dxos/teamwork/issues/415 
- [ ] Console displays only meaningful records 
- [ ] 1 click load Teamwork form KUBE/Console (and it’s clear which version should be loaded)

**HALO:**
- [x] Create new identity
- [x] Download seed phrase
- [ ] Restore identity https://github.com/dxos/teamwork/issues/416 
- [ ] Authorize devices https://github.com/dxos/teamwork/issues/417
- [x] Invite new user to collaborate (w/ pin code sent our of band) 
- [ ] Invite known user to collaborate (w/o needing pin code)
- [ ] Loading state for invitation redeem dialog *NEW* https://github.com/dxos/teamwork/issues/418 

**Party:**
- [x] Create party
- [ ] Rename party https://github.com/dxos/teamwork/issues/419 
- [x] Archive party
- [x] View archived parties
- [x] Unarchive party
- [x] Rename documents inside party 
- [ ] Saving party to IPFS https://github.com/dxos/teamwork/issues/420 
- [ ] Loading party form IPFS https://github.com/dxos/teamwork/issues/421
- [ ] Downloading party snapshot as file https://github.com/dxos/teamwork/issues/422 
- [ ] Restoring party by uploading snapshot file https://github.com/dxos/teamwork/issues/423
- [ ] Activity indicators https://github.com/dxos/teamwork/issues/424
- [ ] Initial sync progress *NEW* https://github.com/dxos/teamwork/issues/425 

**Text editor:**
- [x] Create text document
- [x] Edit text document
- [x] Use chat room right hand side in text document
- [x] Embed planner board inside text document
- [x] Download text document as markdown 
- [x] Publish text to IPFS  
- [x] Make images work w/ IPFS 
- [ ] Changes indicator in both side bar and home screen *NEW*
- [ ] Allow for resizing of images *NEW*
- [ ] Add checkboxes *NEW* 
- [ ] Allow for view-only mode for presentation *NEW*
??? Add paginated scrolling 
??? Allow for horizontal layout 
??? Allow for horizontal scrolling 
??? Allow for raw markdown editor view (like Github) 

**Tasks:**
- [x] Create new task
- [ ] Allow for items to be reordered by dragging *NEW* https://github.com/dxos/teamwork/issues/426
??? Polish Item *NEW*
- [ ] Archiving items *NEW* https://github.com/dxos/teamwork/issues/427
- [ ] Switch to make archived items visible *NEW* https://github.com/dxos/teamwork/issues/428 
- [ ]Unarchiving items *NEW* https://github.com/dxos/teamwork/issues/429
??? Add behavioral rewards for task completion (small, nice sound and animation) 

**Planner:**
- [x] Create planner document
- [x] Option to initialize planner document with standard Kanban columns
- [x] Create new columns 
- [x] Rename columns
- [x] Archive columns
- [x] Create new items
- [x] Rename items
- [x] Archive items
- [x] Switch to make archived columns/items visible
- [x] Unarchiving items/columns

**Chat (aka Messenger):**
- [x] Create chat room
- [x] Messages arrive in correct order across multiple machines
- [x] Use audio/video conference inside chat room (up to 3 people)
- [x] Reference other documents in line
- [x] Download chat logs as markdown 
- [ ] Allow 1:1 DMs *NEW* https://github.com/dxos/teamwork/issues/430  
- [ ] Allow group chats *NEW* https://github.com/dxos/teamwork/issues/431
- [ ] Allow Audio/Video to persist and hover outside of messenger *NEW* https://github.com/dxos/teamwork/issues/432
- [ ] URLs should automatically hotlink instead of being rendered as plain text *NEW* https://github.com/dxos/teamwork/issues/433
- [x] Allow for Audio/Video sources to be set
- [ ] Allow for Audio volume to be adjusted *NEW* https://github.com/dxos/teamwork/issues/434
??? [ ] Allow for blocking / muting individuals *NEW*
??? Allow for gifs to be embedded 

**Bots:**
- [ ] Allow for bot invites https://github.com/dxos/teamwork/issues/435 
- [ ] Invite storage bot to party https://github.com/dxos/teamwork/issues/436 

**Teamwork** 
- [ ] Favicon :) (can be just DXOS logo for now) *NEW* https://github.com/dxos/teamwork/issues/437 
- [ ] Allow for pad-specific links (internal and external) *NEW* https://github.com/dxos/teamwork/issues/438
- [ ] Browser alerts for new notifications *NEW* https://github.com/dxos/teamwork/issues/439 
- [ ] Change indicators for all pad types, showing up in side bar and home screen *NEW* https://github.com/dxos/teamwork/issues/440
- [ ] New message counter in both Teamwork side bar and home screen for messenger pads *NEW* https://github.com/dxos/teamwork/issues/441 
- [ ] Ability to mute notifications for specific pads *NEW* https://github.com/dxos/teamwork/issues/442 
??? Mention/@channel notifications for messenger pads

**Compatibility:**
- [ ] Chrome
- [ ] Brave
- [ ] Firefox 
- [ ] Safari (Mac)
- [ ] Safari (iPad OS)
- [ ] Safari (iOS) *NEW*

**Stability:**
- [ ] All above work for parties up to 10 people with 20 documents (EDITOR 20000char, CHAT 2000msg)
- [ ] All above is tested DAILY (initially by hand) in test parties
- [ ] Each DXOS team has an active party inside Teamwork
- [ ] All internal DXOS meetings have call agendas/notes inside Teamwork
- [ ] Storage bot actually works for 10 people and 20 documents (size?) 

### Out of scope
Features that we discussed multiple times and we want to remember about, but won't fit in this sprint.
- HALO Allow for Github OAUTH 
- HALO Allow for Twitter OAUTH 
- HALO Add Fido 2FA (Yubikeys) 
- HALO Allow for party feature locking based on lack of 2FA (ex. access to planning kanban) 
- Document comments
