### ISSUE TITLE
Tracking issue : Prioritization of near-term teamwork, gravity, and refactoring

### ISSUE THREAD

**Issue by alexwykoff** [dxos/teamwork#384]
**summary**

- [ ] teamwork complete: offline invitations, device management, arena this week, (device prefs)
- [ ] teamwork prep for working on UX next week
- [ ] dmytro drive gravity/testing (with egor)
- [x] get help from thomas on credentials refactoring (typescript, protobufs) (edited) 

**next week**
- [ ] ECHO subscribe/unsubscribe
- [ ] gravity
