### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by richburdon** [dxos/teamwork#4]
- [x] Move Messenger, Planner from incubator.
- [x] Create app and pads for each.
- [ ] Convert all models to use ECHO.
- [ ] Create feature spec for each.
