### ISSUE TITLE
Manual test run Teamwork 0.0.65

### ISSUE THREAD

**Issue by HubertNastaly** [dxos/teamwork#456]
### Instructions:
* Open a new issue and use the format of 'Manual test run' + app + version in the title.
* Use the label of 'QA' for the new issue.
* Update https://github.com/dxos/gravity/blob/main/docs/content/qa/index.md with a link to the new issue.
* If any bugs are found, open new issues if they don't already exist. Add links into the test issue. Add a comment on the issue of the format "Feature: Name of feature : BROKEN"
* Update https://github.com/dxos/gravity/blob/main/docs/content/qa/index.md with a list of broken features with links to the issues.
* When a manual test is added to automation via playwright, remove it from the template.
* Test using 2 machines with 2 different browsers (Brave / Chrome / Firefox are initial targets).
* If that's not possible, use two different profiles of Chrome / Brave on a single machine.
* Reset browser local storage between test runs.
* Each daily run should be a comment in the testing tracking issue with the form below filled out.
* Each person on the QA duty should attach at least one screen recording per week.

### Status:
- [ ] Date: 13 Nov 2020
- [ ] Teamwork version: 0.0.65
- [ ] KUBE: wrn://dxos/application/teamwork@alpha
- [ ] Using: 1 machine
- [ ] Browser 1: Brave
- [ ] Browser 2: Chrome
- [ ] [Video recording](https://drive.google.com/drive/folders/1Mfnij3gPpvXhkfU6JVW_eh6D8HJy7QDF?usp=sharing)

*not sure if all of below should be marked as BROKEN, because some of them have not been implemented yet*

### Basic functionality:
Feature: Redeem offline invitation: BROKEN #455

### Messenger:
*it's hard to verify audio, because screeches are generated when using one machine or two machines next to each other (the sound is getting into feedback loop)*

### Task list:
Feature: Disable adding empty task: BROKEN #454 

### Text editor:
Feature: Messenger in Editor: BROKEN #452 
Feature: Switching between Editors: BROKEN #371 
Feature: Navigating in Editor: BROKEN #382 #453 

### Bots:
*not sure if it is already ready, not working*
- [ ] Invite storage bot to party
- [ ] Verify that storage bot works

### Parties operations:
Feature: Resetting storage: BROKEN #360
