### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by richburdon** [dxos/teamwork#71]
See https://github.com/dxos/teamwork/blob/master/mocks/spec.md for the check list

Polish app for public demo.

- [x] Lots of scrollbars in chrome!
- [x] Fit two rows of cards on Macbook display (scroll vertically)
- [x] Use actual cards for Party cards (find 
- [x] Party image in header
- [x] Reuse click-to-edit component that doesn't shift when editing - https://github.com/dxos/teamwork/issues/183
- [x] Scroll items within card
- [x] Create item should have pop-over below button like google drive (not dialog)
- [x] Invite bot to party (@egorgripasov)

#### PLEASE NOTE:

- [x] standard copyright (DXOS.org)
- [ ] standard imports (grouping and sorting, esp. material-ui standard import syntax)
    - Created https://github.com/dxos/teamwork/issues/122 for this
- [ ] components should be dumb (no major hooks)
- [x] onXXX is a param; handleXXX is an internal event handler
- [x] follow material standards (e.g., Dialog has "DONE" in the footer)
- [x] useStyles should use theme.spacing -- not custom padding/margin or colors
- [ ] use compact sizes for everything
- [ ] less text (use icons)
- [x] add classes to modify thing (e.g., clsx("card", "unsubscribed") not "unsubscribedCard")

If in doubt look for something similar in react-appkit

#### TODO:

- [ ] fix document/item scrolling
- [x] members and create button should be on same bottom line of party card
- [ ] sharing table should have fixed width cells (for content type)
- [x] smaller avatars (in party card and sharing dialog)
- [ ] add spacing to party card grid
- [x] move sharing dialog to appkit (discuss with Max)
- [ ] create storybook for UX components (too slow to test inside the app!)
